#!/usr/bin/env ruby

require 'tempfile'


commit_log = `git log -1 --pretty`.chomp

m, commit_id = * commit_log.match(/commit\W*([A-Fa-f0-9]+)/)


Tempfile.open('ticgit_comment') do |tmp|
  tmp.write commit_log
  actions = {}

  #puts 'TicGit post-commit called'

  # comment on checked out ticket
  my_tickets = `ti show`.chomp

  my_tickets.scan(/^TicId:\s([a-fA-F0-9]+)$/).each do |id|
        puts id
	actions[id] = :ref
  end

  # comment on any tickets this commit references
  commit_log.scan(/\(\W*[Rr]efs?\W*:*\W*\#([a-fA-F0-9]+)\W*\)/).each do |id|
    	actions[id] = :ref
  end

  # close any tickets this commit solves
  # overwrite any refs, as the commit log will still
  # be added to the ticket as a comment, but will also be closed
  commit_log.scan(/\(\W*[Cc]loses\W*:*\W*\#([a-fA-F0-9]+)\W*\)/).each do |id|
    actions[id] = :close
  end

  actions.each do |id, action|
    tmp.rewind
    `ti comment #{id} --file #{tmp.path} --message "<pre>#{tmp.read}</pre>"` if action
    `ti state #{id} resolved` if action == :close
  end
end
